export const homelessHouseholds: IHomelessHouseholds[] = [
  {
    age: 31,
    decision: "no priority need",
    decisionCode: 3,
    decisionDate: new Date("2015-09-30T00:00:00.000Z"),
    ethnicity: "Other",
    id: 7158,
    nationality: "Not Rec",
    need: "vulnerable - physical",
    reason: "eviction - parents",
  },
  {
    age: 47,
    decision: "approved permanent rehous",
    decisionCode: 1,
    decisionDate: new Date("2015-09-30T00:00:00.000Z"),
    ethnicity: "Black/BlkBrit: African",
    id: 7159,
    nationality: "Not Rec",
    need: "dependent children",
    reason: "end AST not arrears",
  },
  {
    age: 27,
    decision: "approved permanent rehous",
    decisionCode: 1,
    decisionDate: new Date("2015-09-30T00:00:00.000Z"),
    ethnicity: "White: British",
    id: 7161,
    nationality: "Not Rec",
    need: "dependent children",
    reason: "DV - partner",
  }
];